### PR TITLE
remove using std & correctly namespace to std

### PR DESCRIPTION
**Pull request by whackashoe**
using std is a bad practice for files intended to be included. this changes that.

### CODE REVIEW

**Comment by aimran** [comment]
@whackashoe 

Do you still want me to merge #3 and #4 (in light of the re-work you are about to do)?

One thing I should mention — I use traildb-cpp to power traildb-r (latter makes use of the cpp wrapper to make create handy R functions). Therefore, it would be necessary to keep the functions backward compatible.

**Comment by aimran** [comment]
No worries. I merged the changes.

**Comment by whackashoe** [comment]
@aimran ok, ill see but most likely wont keep them backward compatible in my next pr, but perhaps we can modify corresponding R code to match from there? what do you think? It'll be at least a few days until that's ready though. I suppose we could be able to make a corresponding change to traildb-r to fit it? is there anything special i should know regarding that, would it be a matter of just changing names, params, or do we have backward compat to worry about? (im basically assuming that isnt the case so far as this is so new, but excuse me if that's incorrect!) thanks!

**Comment by aimran** [comment]
@whackashoe Carry on I say. I will adjust things accordingly on the R side of things (I am relying on the `getters` mostly so as long as the functions return the same we should be okay). I may not be as fast merging this time around but we will live. Cheers

**Pull request merged**
